In [ ]:
import numpy as np
import pandas as pd

### GSE57957

In [ ]:
gpl_df = pd.read_table('GPL10558-50081.txt', skiprows=30)
deg_df = pd.read_table('topconfects - GSE57957.txt', names=['ID'])

In [ ]:
gpl_df.head(25)

,ID,Species,Source,Search_Key,Transcript,ILMN_Gene,Source_Reference_ID,RefSeq_ID,Unigene_ID,Entrez_Gene_ID,...,Probe_Chr_Orientation,Probe_Coordinates,Cytoband,Definition,Ontology_Component,Ontology_Process,Ontology_Function,Synonyms,Obsolete_Probe_Id,GB_ACC
0,ILMN_1343048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ILMN_1343049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ILMN_1343050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ILMN_1343052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ILMN_1343059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ILMN_1343061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ILMN_1343062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ILMN_1343063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ILMN_1343064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ILMN_1343291,Homo sapiens,RefSeq,NM_001402.4,ILMN_5311,EEF1A1,NM_001402.5,NM_001402.5,NaN,1915.0,...,-,74284362-74284378:74284474-74284506,6q13c,Homo sapiens eukaryotic translation elongation...,All of the contents of a cell excluding the pl...,The successive addition of amino acid residues...,"Interacting selectively with a nucleotide, any...",EEF1A; FLJ25721; CCS-3; PTI1; CCS3; MGC102687;...,EEF1A; PTI1; MGC16224; eEF1A-1; EF-Tu; EEF-1; ...,NM_001402.5
10,ILMN_1343295,Homo sapiens,RefSeq,NaN,ILMN_27206,GAPDH,NM_002046.3,NM_002046.3,NaN,2597.0,...,+,6517320-6517369,12p13.31d,Homo sapiens glyceraldehyde-3-phosphate dehydr...,All of the contents of a cell excluding the pl...,The chemical reactions and pathways involving ...,Catalysis of a biochemical reaction at physiol...,G3PD; GAPD; MGC88685,GAPD; MGC88685; G3PD,NM_002046.3
11,ILMN_1343296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ILMN_1343297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ILMN_1343298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ILMN_1343299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ILMN_1343300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ILMN_1343301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ILMN_1343302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,ILMN_1343303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ILMN_1343304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,ILMN_1343305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ILMN_1343306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ILMN_1343307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ILMN_1343308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,ILMN_1343309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
gpl_df.tail(25)

,ID,Species,Source,Search_Key,Transcript,ILMN_Gene,Source_Reference_ID,RefSeq_ID,Unigene_ID,Entrez_Gene_ID,...,Probe_Chr_Orientation,Probe_Coordinates,Cytoband,Definition,Ontology_Component,Ontology_Process,Ontology_Function,Synonyms,Obsolete_Probe_Id,GB_ACC
48082,ILMN_3311070,Homo sapiens,RefSeq,NR_030361.1,ILMN_388131,MIR33B,NR_030361.1,NR_030361.1,NaN,693120.0,...,NaN,NaN,17p11.2g,"Homo sapiens microRNA 33b (MIR33B), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_030361.1
48083,ILMN_3311075,Homo sapiens,RefSeq,NR_031736.1,ILMN_388655,MIR1915,NR_031736.1,NR_031736.1,NaN,100302129.0,...,NaN,NaN,NaN,"Homo sapiens microRNA 1915 (MIR1915), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_031736.1
48084,ILMN_3311080,Homo sapiens,RefSeq,NR_030165.1,ILMN_387798,MIR490,NR_030165.1,NR_030165.1,NaN,574443.0,...,NaN,NaN,7q33d,"Homo sapiens microRNA 490 (MIR490), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_030165.1
48085,ILMN_3311085,Homo sapiens,RefSeq,NR_003194.1,ILMN_165933,SNORD114-2,NR_003194.1,NR_003194.1,NaN,767578.0,...,+,100487960-100488009,14q32.31a,"Homo sapiens small nucleolar RNA, C/D box 114-...",NaN,NaN,NaN,14q(II-2),14q(II-2),NR_003194.1
48086,ILMN_3311090,Homo sapiens,RefSeq,NR_030294.1,ILMN_388015,MIR551B,NR_030294.1,NR_030294.1,NaN,693136.0,...,NaN,NaN,3q26.2a,"Homo sapiens microRNA 551b (MIR551B), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_030294.1
48087,ILMN_3311095,Homo sapiens,RefSeq,NR_030373.1,ILMN_388175,MIR643,NR_030373.1,NR_030373.1,NaN,693228.0,...,NaN,NaN,19q13.33e,"Homo sapiens microRNA 643 (MIR643), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_030373.1
48088,ILMN_3311100,Homo sapiens,RefSeq,NR_029476.1,ILMN_387943,MIRLET7A1,NR_029476.1,NR_029476.1,NaN,406881.0,...,NaN,NaN,9q22.32a,"Homo sapiens microRNA let-7a-1 (MIRLET7A1), mi...",NaN,NaN,NaN,NaN,NaN,NR_029476.1
48089,ILMN_3311105,Homo sapiens,RefSeq,NR_003206.1,ILMN_162444,SNORD114-13,NR_003206.1,NR_003206.1,NaN,767591.0,...,+,100505970-100506019,14q32.31a,"Homo sapiens small nucleolar RNA, C/D box 114-...",NaN,NaN,NaN,14q(II-13),14q(II-13),NR_003206.1
48090,ILMN_3311110,Homo sapiens,RefSeq,NR_029899.1,ILMN_387777,MIR335,NR_029899.1,NR_029899.1,NaN,442904.0,...,NaN,NaN,7q32.2b,"Homo sapiens microRNA 335 (MIR335), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_029899.1
48091,ILMN_3311115,Homo sapiens,RefSeq,NR_031608.1,ILMN_388711,MIR663B,NR_031608.1,NR_031608.1,NaN,100313824.0,...,NaN,NaN,NaN,"Homo sapiens microRNA 663b (MIR663B), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_031608.1
48092,ILMN_3311120,Homo sapiens,RefSeq,NR_031686.1,ILMN_388736,MIR548P,NR_031686.1,NR_031686.1,NaN,100302288.0,...,NaN,NaN,NaN,"Homo sapiens microRNA 548p (MIR548P), microRNA.",NaN,NaN,NaN,NaN,NaN,NR_031686.1
48093,ILMN_3311125,Homo sapiens,RefSeq,NR_031565.1,ILMN_388705,MIR320C1,NR_031565.1,NR_031565.1,NaN,100302135.0,...,NaN,NaN,NaN,"Homo sapiens microRNA 320c-1 (MIR320C1), micro...",NaN,NaN,NaN,NaN,NaN,NR_031565.1
48094,ILMN_3311130,Homo sapiens,RefSeq,NR_031702.1,ILMN_388745,MIR1255B2,NR_031702.1,NR_031702.1,NaN,100313835.0,...,NaN,NaN,NaN,"Homo sapiens microRNA 1255b-2 (MIR1255B2), mic...",NaN,NaN,NaN,NaN,NaN,NR_031702.1
48095,ILMN_3311135,Homo sapiens,RefSeq,XM_002342102.1,ILMN_373338,FOXO6,XM_002342102.1,XM_002342102.1,NaN,100132074.0,...,NaN,NaN,1p34.2c,PREDICTED: Homo sapiens forkhead box protein O...,A membrane-bounded organelle of eukaryotic cel...,The synthesis of either RNA on a template of D...,The function of binding to a specific DNA sequ...,NaN,NaN,XM_002342102.1
48096,ILMN_3311140,Homo sapiens,RefSeq,NR_027012.1,ILMN_387222,BEYLA,NR_027012.1,NR_027012.1,NaN,497634.0,...,+,47767182-47767231,NaN,"Homo sapiens hypothetical LOC497634 (BEYLA), t...",NaN,NaN,NaN,NaN,NaN,NR_027012.1
48097,ILMN_3311145,Homo sapiens,RefSeq,XR_079546.1,ILMN_379410,MGC11082,XR_079546.1,XR_079546.1,NaN,84777.0,...,NaN,NaN,NaN,PREDICTED: Homo sapiens hypothetical LOC84777 ...,NaN,NaN,NaN,NaN,NaN,XR_079546.1
48098,ILMN_3311150,Homo sapiens,RefSeq,NR_027013.1,ILMN_387226,BEYLA,NR_027013.1,NR_027013.1,NaN,497634.0,...,+,47761060-47761109,NaN,"Homo sapiens hypothetical LOC497634 (BEYLA), t...",NaN,NaN,NaN,NaN,NaN,NR_027013.1
48099,ILMN_3311155,Homo sapiens,RefSeq,XM_002346379.1,ILMN_376984,FOXO6,XM_002346379.1,XM_002346379.1,NaN,100132074.0,...,NaN,NaN,1p34.2c,PREDICTED: Homo sapiens forkhead box protein O...,A membrane-bounded organelle of eukaryotic cel...,The synthesis of either RNA on a template of D...,The function of binding to a specific DNA sequ...,NaN,NaN,XM_002346379.1
48100,ILMN_3311160,Homo sapiens,RefSeq,XR_079560.1,ILMN_382629,MGC11082,XR_079560.1,XR_079560.1,NaN,84777.0,...,NaN,NaN,NaN,PREDICTED: Homo sapiens hypothetical LOC84777 ...,NaN,NaN,NaN,NaN,NaN,XR_079560.1
48101,ILMN_3311165,Homo sapiens,RefSeq,NR_027345.1,ILMN_387355,NCRNA00173,NR_027345.1,NR_027345.1,NaN,100287569.0,...,NaN,NaN,NaN,Homo sapiens non-protein coding RNA 173 (NCRNA...,NaN,NaN,NaN,NaN,NaN,NR_027345.1
48102,ILMN_3311170,Homo sapiens,RefSeq,XR_040141.2,ILMN_381882,SKCG-1,XR_040141.2,XR_040141.2,NaN,100049615.0,...,NaN,NaN,11q22.3d,PREDICTED: Homo sapiens sporadic kidney cancer...,NaN,NaN,NaN,NaN,NaN,XR_040141.2
48103,ILMN_3311175,Homo sapiens,RefSeq,XR_079076.1,ILMN_381617,ESP33,XR_079076.1,XR_079076.1,NaN,100188917.0,...,NaN,NaN,NaN,PREDICTED: Homo sapiens hypothetical locus ESP...,NaN,NaN,NaN,NaN,NaN,XR_079076.1
48104,ILMN_3311180,Homo sapiens,RefSeq,XR_040140.2,ILMN_375317,SKCG-1,XR_040140.2,XR_040140.2,NaN,100049615.0,...,NaN,NaN,11q22.3d,PREDICTED: Homo sapiens sporadic kidney cancer...,NaN,NaN,NaN,NaN,NaN,XR_040140.2
48105,ILMN_3311185,Homo sapiens,RefSeq,XR_078679.1,ILMN_375026,ESP33,XR_078679.1,XR_078679.1,NaN,100188917.0,...,NaN,NaN,NaN,PREDICTED: Homo sapiens hypothetical locus ESP...,NaN,NaN,NaN,NaN,NaN,XR_078679.1
48106,ILMN_3311190,Homo sapiens,RefSeq,NR_027346.1,ILMN_387358,NCRNA00173,NR_027346.1,NR_027346.1,NaN,100287569.0,...,NaN,NaN,NaN,Homo sapiens non-protein coding RNA 173 (NCRNA...,NaN,NaN,NaN,NaN,NaN,NR_027346.1

In [ ]:
gpl_df.columns

Index(['ID', 'Species', 'Source', 'Search_Key', 'Transcript', 'ILMN_Gene',
       'Source_Reference_ID', 'RefSeq_ID', 'Unigene_ID', 'Entrez_Gene_ID',
       'GI', 'Accession', 'Symbol', 'Protein_Product', 'Probe_Id',
       'Array_Address_Id', 'Probe_Type', 'Probe_Start', 'SEQUENCE',
       'Chromosome', 'Probe_Chr_Orientation', 'Probe_Coordinates', 'Cytoband',
       'Definition', 'Ontology_Component', 'Ontology_Process',
       'Ontology_Function', 'Synonyms', 'Obsolete_Probe_Id', 'GB_ACC'],
      dtype='object')

In [ ]:
deg_df.head()

             ID
0  ILMN_1797519
1  ILMN_2051972
2  ILMN_1782754
3  ILMN_1672148
4  ILMN_2278335

In [ ]:
deg_df.tail()

                 ID
47318  ILMN_1728858
47319  ILMN_1782845
47320  ILMN_1714882
47321  ILMN_1713321
47322  ILMN_1659290

In [ ]:
deg_df.shape

(47323, 1)

In [ ]:
merged_df = pd.merge(deg_df, gpl_df, on='ID')

In [ ]:
merged_df.dropna(subset=['ILMN_Gene'], inplace=True)

In [ ]:
merged_df.shape

(47323, 30)

In [ ]:
gene_list = merged_df['ILMN_Gene'].to_list()

In [ ]:
merged_df['ILMN_Gene'].to_csv('gse57957.csv', index=False)

### GSE62232

In [ ]:
gpl_df = pd.read_table('GPL570-55999.txt', skiprows=16)
deg_df = pd.read_table('topconfects - GSE62232.txt', names=['ID'])

<ipython-input-12-b8f412f83b2f>:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  gpl_df = pd.read_table('GPL570-55999.txt', skiprows=16)

In [ ]:
gpl_df.head(25)

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
0,1007_s_at,U48705,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,U48705 /FEATURE=mRNA /DEFINITION=HSU48705 Huma...,U48705,discoidin domain receptor tyrosine kinase 1 //...,DDR1 /// MIR4640,780 /// 100616237,NM_001202521 /// NM_001202522 /// NM_001202523...,0001558 // regulation of cell growth // inferr...,0005576 // extracellular region // inferred fr...,0000166 // nucleotide binding // inferred from...
1,1053_at,M87338,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M87338 /FEATURE= /DEFINITION=HUMA1SBU Human re...,M87338,"replication factor C (activator 1) 2, 40kDa",RFC2,5982,NM_001278791 /// NM_001278792 /// NM_001278793...,0000278 // mitotic cell cycle // traceable aut...,0005634 // nucleus // inferred from electronic...,0000166 // nucleotide binding // inferred from...
2,117_at,X51757,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X51757 /FEATURE=cds /DEFINITION=HSP70B Human h...,X51757,heat shock 70kDa protein 6 (HSP70B'),HSPA6,3310,NM_002155,0000902 // cell morphogenesis // inferred from...,0005737 // cytoplasm // inferred from direct a...,0000166 // nucleotide binding // inferred from...
3,121_at,X69699,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,X69699 /FEATURE= /DEFINITION=HSPAX8A H.sapiens...,X69699,paired box 8,PAX8,7849,NM_003466 /// NM_013951 /// NM_013952 /// NM_0...,0001655 // urogenital system development // in...,0005634 // nucleus // inferred from direct ass...,0000979 // RNA polymerase II core promoter seq...
4,1255_g_at,L36861,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L36861 /FEATURE=expanded_cds /DEFINITION=HUMGC...,L36861,guanylate cyclase activator 1A (retina),GUCA1A,2978,NM_000409 /// XM_006715073,0007165 // signal transduction // non-traceabl...,0001750 // photoreceptor outer segment // infe...,0005509 // calcium ion binding // inferred fro...
5,1294_at,L13852,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,L13852 /FEATURE= /DEFINITION=HUME1URP Homo sap...,L13852,microRNA 5193 /// ubiquitin-like modifier acti...,MIR5193 /// UBA7,7318 /// 100847079,NM_003335 /// NR_049825 /// XM_005265430 /// X...,0006464 // cellular protein modification proce...,0005634 // nucleus // not recorded /// 0005829...,0000166 // nucleotide binding // inferred from...
6,1316_at,X55005,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X55005 /FEATURE=mRNA /DEFINITION=HSCERBAR Homo...,X55005,"thyroid hormone receptor, alpha",THRA,7067,NM_001190918 /// NM_001190919 /// NM_003250 //...,0000122 // negative regulation of transcriptio...,0000790 // nuclear chromatin // inferred from ...,0000978 // RNA polymerase II core promoter pro...
7,1320_at,X79510,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X79510 /FEATURE=cds /DEFINITION=HSPTPD1 H.sapi...,X79510,"protein tyrosine phosphatase, non-receptor typ...",PTPN21,11099,NM_007039 /// XM_005267287 /// XM_006720011,0006470 // protein dephosphorylation // tracea...,0005737 // cytoplasm // inferred from electron...,0004721 // phosphoprotein phosphatase activity...
8,1405_i_at,M21121,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M21121 /FEATURE= /DEFINITION=HUMTCSM Human T c...,M21121,chemokine (C-C motif) ligand 5,CCL5,6352,NM_001278736 /// NM_002985,0000165 // MAPK cascade // inferred from mutan...,0005576 // extracellular region // traceable a...,0004435 // phosphatidylinositol phospholipase ...
9,1431_at,J02843,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,J02843 /FEATURE=cds /DEFINITION=HUMCYPIIE Huma...,J02843,"cytochrome P450, family 2, subfamily E, polype...",CYP2E1,1571,NM_000773,0006641 // triglyceride metabolic process // i...,0000139 // Golgi membrane // inferred from ele...,0004497 // monooxygenase activity // inferred ...
10,1438_at,X75208,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X75208 /FEATURE=cds /DEFINITION=HSPTKR H.sapie...,X75208,EPH receptor B3,EPHB3,2049,NM_004443,0001525 // angiogenesis // inferred from seque...,0005886 // plasma membrane // inferred from el...,0000166 // nucleotide binding // inferred from...
11,1487_at,L38487,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L38487 /FEATURE=mRNA /DEFINITION=HUMHERRA1 Hum...,L38487,estrogen-related receptor alpha,ESRRA,2101,NM_001282450 /// NM_001282451 /// NM_004451 //...,"0006351 // transcription, DNA-templated // inf...",0005634 // nucleus // inferred from direct ass...,0003677 // DNA binding // traceable author sta...
12,1494_f_at,M33318,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,M33318 /FEATURE=mRNA /DEFINITION=HUMCPIIA3A Hu...,M33318,"cytochrome P450, family 2, subfamily A, polype...",CYP2A6,1548,NM_000762,0006805 // xenobiotic metabolic process // tra...,0005783 // endoplasmic reticulum // inferred f...,0004497 // monooxygenase activity // inferred ...
13,1552256_a_at,NM_005505,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_005505.2 /DB_XREF=gi:21361199 /GEN=SCARB...,NM_005505,"scavenger receptor class B, member 1",SCARB1,949,NM_001082959 /// NM_005505,0001935 // endothelial cell proliferation // i...,0005737 // cytoplasm // inferred from electron...,0001530 // lipopolysaccharide binding // infer...
14,1552257_a_at,NM_015140,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_015140.1 /DB_XREF=gi:11056035 /TID=Hs2.8...,NM_015140,"tubulin tyrosine ligase-like family, member 12",TTLL12,23170,NM_015140,0006464 // cellular protein modification proce...,NaN,NaN
15,1552258_at,NM_052871,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_052871.1 /DB_XREF=gi:16418372 /TID=Hs2.4...,NM_052871,long intergenic non-protein coding RNA 152 ///...,LINC00152 /// LOC101930489,112597 /// 101930489,NM_052871 /// NR_024204 /// NR_024205 /// NR_0...,NaN,NaN,NaN
16,1552261_at,NM_080735,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_080735.1 /DB_XREF=gi:18379359 /GEN=WFDC2...,NM_080735,WAP four-disulfide core domain 2,WFDC2,10406,NM_006103 /// NM_080733 /// NM_080734 /// NM_0...,0006508 // proteolysis // traceable author sta...,0005576 // extracellular region // inferred fr...,0004866 // endopeptidase inhibitor activity //...
17,1552263_at,NM_138957,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138957.1 /DB_XREF=gi:20986530 /GEN=MAPK1...,NM_138957,mitogen-activated protein kinase 1,MAPK1,5594,NM_002745 /// NM_138957,0000165 // MAPK cascade // traceable author st...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // inferred from...
18,1552264_a_at,NM_138957,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138957.1 /DB_XREF=gi:20986530 /GEN=MAPK1...,NM_138957,mitogen-activated protein kinase 1,MAPK1,5594,NM_002745 /// NM_138957,0000165 // MAPK cascade // traceable author st...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // inferred from...
19,1552266_at,NM_145004,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_145004.1 /DB_XREF=gi:21450712 /TID=Hs2.3...,NM_145004,ADAM metallopeptidase domain 32,ADAM32,203102,NM_145004 /// XM_006716298 /// XM_006716299 //...,0006508 // proteolysis // inferred from electr...,0016020 // membrane // inferred from electroni...,0004222 // metalloendopeptidase activity // in...
20,1552269_at,NM_138796,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138796.1 /DB_XREF=gi:20270344 /TID=Hs2.9...,NM_138796,spermatogenesis associated 17,SPATA17,128153,NM_138796 /// XM_005273052 /// XM_006711165,NaN,0005737 // cytoplasm // inferred from electron...,0005515 // protein binding // inferred from el...
21,1552271_at,NM_153359,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_153359.1 /DB_XREF=gi:23503298 /TID=Hs2.2...,NM_153359,proline rich 22,PRR22,163154,NM_001134316 /// NM_153359,NaN,NaN,NaN
22,1552272_a_at,NM_153359,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_153359.1 /DB_XREF=gi:23503298 /TID=Hs2.2...,NM_153359,proline rich 22,PRR22,163154,NM_001134316 /// NM_153359,NaN,NaN,NaN
23,1552274_at,BC014479,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:BC014479.1 /DB_XREF=gi:15680248 /TID=Hs2.32...,BC014479,PX domain containing serine/threonine kinase,PXK,54899,NM_001289095 /// NM_001289096 /// NM_001289098...,0006468 // protein phosphorylation // non-trac...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // non-traceable...
24,1552275_s_at,BG573647,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:BG573647 /DB_XREF=gi:13581300 /DB_XREF=6025...,BG573647,PX domain containing serine/threonine kinase,PXK,54899,NM_001289095 /// NM_001289096 /// NM_001289098...,0006468 // protein phosphorylation // non-trac...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // non-traceable...

In [ ]:
gpl_df.tail(25)

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
54650,AFFX-r2-Bs-dap-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=dapB, jojF /DB_XREF=gb:L38424...",AFFX-r2-Bs-dap-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54651,AFFX-r2-Bs-lys-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54652,AFFX-r2-Bs-lys-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54653,AFFX-r2-Bs-lys-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54654,AFFX-r2-Bs-phe-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheB /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54655,AFFX-r2-Bs-phe-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheA /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54656,AFFX-r2-Bs-phe-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheA /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54657,AFFX-r2-Bs-thr-3_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrB /DB_XREF=gb:X04603.1 /NO...,AFFX-r2-Bs-thr-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54658,AFFX-r2-Bs-thr-5_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-r2-Bs-thr-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54659,AFFX-r2-Bs-thr-M_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-r2-Bs-thr-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54660,AFFX-r2-Ec-bioB-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54661,AFFX-r2-Ec-bioB-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54662,AFFX-r2-Ec-bioB-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54663,AFFX-r2-Ec-bioC-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioC /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioC-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54664,AFFX-r2-Ec-bioC-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioC /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioC-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54665,AFFX-r2-Ec-bioD-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioD /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioD-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54666,AFFX-r2-Ec-bioD-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioD /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioD-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54667,AFFX-r2-P1-cre-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,Bacteriophage P1 /GEN=cre /DB_XREF=gb:X03453.1...,AFFX-r2-P1-cre-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54668,AFFX-r2-P1-cre-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,Bacteriophage P1 /GEN=cre /DB_XREF=gb:X03453.1...,AFFX-r2-P1-cre-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54669,AFFX-ThrX-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrB /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54670,AFFX-ThrX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54671,AFFX-ThrX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-ThrX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54672,AFFX-TrpnX-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpC, trpF /DB_XREF=gb:K01391...",AFFX-TrpnX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54673,AFFX-TrpnX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpE, trpD /DB_XREF=gb:K01391...",AFFX-TrpnX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54674,AFFX-TrpnX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpD, trpC /DB_XREF=gb:K01391...",AFFX-TrpnX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
gpl_df.columns

Index(['ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date',
       'Sequence Type', 'Sequence Source', 'Target Description',
       'Representative Public ID', 'Gene Title', 'Gene Symbol',
       'ENTREZ_GENE_ID', 'RefSeq Transcript ID',
       'Gene Ontology Biological Process', 'Gene Ontology Cellular Component',
       'Gene Ontology Molecular Function'],
      dtype='object')

In [ ]:
deg_df.head()

             ID
0     1255_g_at
1    1552266_at
2    1552269_at
3    1552296_at
4  1552320_a_at

In [ ]:
deg_df.tail()

                   ID
9536   AFFX-ThrX-5_at
9537   AFFX-ThrX-M_at
9538  AFFX-TrpnX-3_at
9539  AFFX-TrpnX-5_at
9540  AFFX-TrpnX-M_at

In [ ]:
deg_df.shape

(9541, 1)

In [ ]:
merged_df_2 = pd.merge(deg_df, gpl_df, on='ID')

In [ ]:
merged_df_2.dropna(subset=['Gene Symbol'], inplace=True)

In [ ]:
merged_df_2.shape

(6529, 16)

In [ ]:
gene_list = merged_df_2['Gene Symbol'].to_list()

In [ ]:
merged_df_2['Gene Symbol'].to_csv('gse62232.csv', index=False)

### GSE112790

In [ ]:
gpl_df = pd.read_table('GPL570-55999.txt', skiprows=16)
deg_df = pd.read_table('topconfects - GSE112790.txt', names=['ID'])

<ipython-input-24-79f15b129fbd>:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  gpl_df = pd.read_table('GPL570-55999.txt', skiprows=16)

In [ ]:
gpl_df.head(25)

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
0,1007_s_at,U48705,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,U48705 /FEATURE=mRNA /DEFINITION=HSU48705 Huma...,U48705,discoidin domain receptor tyrosine kinase 1 //...,DDR1 /// MIR4640,780 /// 100616237,NM_001202521 /// NM_001202522 /// NM_001202523...,0001558 // regulation of cell growth // inferr...,0005576 // extracellular region // inferred fr...,0000166 // nucleotide binding // inferred from...
1,1053_at,M87338,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M87338 /FEATURE= /DEFINITION=HUMA1SBU Human re...,M87338,"replication factor C (activator 1) 2, 40kDa",RFC2,5982,NM_001278791 /// NM_001278792 /// NM_001278793...,0000278 // mitotic cell cycle // traceable aut...,0005634 // nucleus // inferred from electronic...,0000166 // nucleotide binding // inferred from...
2,117_at,X51757,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X51757 /FEATURE=cds /DEFINITION=HSP70B Human h...,X51757,heat shock 70kDa protein 6 (HSP70B'),HSPA6,3310,NM_002155,0000902 // cell morphogenesis // inferred from...,0005737 // cytoplasm // inferred from direct a...,0000166 // nucleotide binding // inferred from...
3,121_at,X69699,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,X69699 /FEATURE= /DEFINITION=HSPAX8A H.sapiens...,X69699,paired box 8,PAX8,7849,NM_003466 /// NM_013951 /// NM_013952 /// NM_0...,0001655 // urogenital system development // in...,0005634 // nucleus // inferred from direct ass...,0000979 // RNA polymerase II core promoter seq...
4,1255_g_at,L36861,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L36861 /FEATURE=expanded_cds /DEFINITION=HUMGC...,L36861,guanylate cyclase activator 1A (retina),GUCA1A,2978,NM_000409 /// XM_006715073,0007165 // signal transduction // non-traceabl...,0001750 // photoreceptor outer segment // infe...,0005509 // calcium ion binding // inferred fro...
5,1294_at,L13852,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,L13852 /FEATURE= /DEFINITION=HUME1URP Homo sap...,L13852,microRNA 5193 /// ubiquitin-like modifier acti...,MIR5193 /// UBA7,7318 /// 100847079,NM_003335 /// NR_049825 /// XM_005265430 /// X...,0006464 // cellular protein modification proce...,0005634 // nucleus // not recorded /// 0005829...,0000166 // nucleotide binding // inferred from...
6,1316_at,X55005,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X55005 /FEATURE=mRNA /DEFINITION=HSCERBAR Homo...,X55005,"thyroid hormone receptor, alpha",THRA,7067,NM_001190918 /// NM_001190919 /// NM_003250 //...,0000122 // negative regulation of transcriptio...,0000790 // nuclear chromatin // inferred from ...,0000978 // RNA polymerase II core promoter pro...
7,1320_at,X79510,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X79510 /FEATURE=cds /DEFINITION=HSPTPD1 H.sapi...,X79510,"protein tyrosine phosphatase, non-receptor typ...",PTPN21,11099,NM_007039 /// XM_005267287 /// XM_006720011,0006470 // protein dephosphorylation // tracea...,0005737 // cytoplasm // inferred from electron...,0004721 // phosphoprotein phosphatase activity...
8,1405_i_at,M21121,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M21121 /FEATURE= /DEFINITION=HUMTCSM Human T c...,M21121,chemokine (C-C motif) ligand 5,CCL5,6352,NM_001278736 /// NM_002985,0000165 // MAPK cascade // inferred from mutan...,0005576 // extracellular region // traceable a...,0004435 // phosphatidylinositol phospholipase ...
9,1431_at,J02843,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,J02843 /FEATURE=cds /DEFINITION=HUMCYPIIE Huma...,J02843,"cytochrome P450, family 2, subfamily E, polype...",CYP2E1,1571,NM_000773,0006641 // triglyceride metabolic process // i...,0000139 // Golgi membrane // inferred from ele...,0004497 // monooxygenase activity // inferred ...
10,1438_at,X75208,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X75208 /FEATURE=cds /DEFINITION=HSPTKR H.sapie...,X75208,EPH receptor B3,EPHB3,2049,NM_004443,0001525 // angiogenesis // inferred from seque...,0005886 // plasma membrane // inferred from el...,0000166 // nucleotide binding // inferred from...
11,1487_at,L38487,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L38487 /FEATURE=mRNA /DEFINITION=HUMHERRA1 Hum...,L38487,estrogen-related receptor alpha,ESRRA,2101,NM_001282450 /// NM_001282451 /// NM_004451 //...,"0006351 // transcription, DNA-templated // inf...",0005634 // nucleus // inferred from direct ass...,0003677 // DNA binding // traceable author sta...
12,1494_f_at,M33318,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,M33318 /FEATURE=mRNA /DEFINITION=HUMCPIIA3A Hu...,M33318,"cytochrome P450, family 2, subfamily A, polype...",CYP2A6,1548,NM_000762,0006805 // xenobiotic metabolic process // tra...,0005783 // endoplasmic reticulum // inferred f...,0004497 // monooxygenase activity // inferred ...
13,1552256_a_at,NM_005505,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_005505.2 /DB_XREF=gi:21361199 /GEN=SCARB...,NM_005505,"scavenger receptor class B, member 1",SCARB1,949,NM_001082959 /// NM_005505,0001935 // endothelial cell proliferation // i...,0005737 // cytoplasm // inferred from electron...,0001530 // lipopolysaccharide binding // infer...
14,1552257_a_at,NM_015140,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_015140.1 /DB_XREF=gi:11056035 /TID=Hs2.8...,NM_015140,"tubulin tyrosine ligase-like family, member 12",TTLL12,23170,NM_015140,0006464 // cellular protein modification proce...,NaN,NaN
15,1552258_at,NM_052871,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_052871.1 /DB_XREF=gi:16418372 /TID=Hs2.4...,NM_052871,long intergenic non-protein coding RNA 152 ///...,LINC00152 /// LOC101930489,112597 /// 101930489,NM_052871 /// NR_024204 /// NR_024205 /// NR_0...,NaN,NaN,NaN
16,1552261_at,NM_080735,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_080735.1 /DB_XREF=gi:18379359 /GEN=WFDC2...,NM_080735,WAP four-disulfide core domain 2,WFDC2,10406,NM_006103 /// NM_080733 /// NM_080734 /// NM_0...,0006508 // proteolysis // traceable author sta...,0005576 // extracellular region // inferred fr...,0004866 // endopeptidase inhibitor activity //...
17,1552263_at,NM_138957,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138957.1 /DB_XREF=gi:20986530 /GEN=MAPK1...,NM_138957,mitogen-activated protein kinase 1,MAPK1,5594,NM_002745 /// NM_138957,0000165 // MAPK cascade // traceable author st...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // inferred from...
18,1552264_a_at,NM_138957,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138957.1 /DB_XREF=gi:20986530 /GEN=MAPK1...,NM_138957,mitogen-activated protein kinase 1,MAPK1,5594,NM_002745 /// NM_138957,0000165 // MAPK cascade // traceable author st...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // inferred from...
19,1552266_at,NM_145004,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_145004.1 /DB_XREF=gi:21450712 /TID=Hs2.3...,NM_145004,ADAM metallopeptidase domain 32,ADAM32,203102,NM_145004 /// XM_006716298 /// XM_006716299 //...,0006508 // proteolysis // inferred from electr...,0016020 // membrane // inferred from electroni...,0004222 // metalloendopeptidase activity // in...
20,1552269_at,NM_138796,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_138796.1 /DB_XREF=gi:20270344 /TID=Hs2.9...,NM_138796,spermatogenesis associated 17,SPATA17,128153,NM_138796 /// XM_005273052 /// XM_006711165,NaN,0005737 // cytoplasm // inferred from electron...,0005515 // protein binding // inferred from el...
21,1552271_at,NM_153359,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_153359.1 /DB_XREF=gi:23503298 /TID=Hs2.2...,NM_153359,proline rich 22,PRR22,163154,NM_001134316 /// NM_153359,NaN,NaN,NaN
22,1552272_a_at,NM_153359,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:NM_153359.1 /DB_XREF=gi:23503298 /TID=Hs2.2...,NM_153359,proline rich 22,PRR22,163154,NM_001134316 /// NM_153359,NaN,NaN,NaN
23,1552274_at,BC014479,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:BC014479.1 /DB_XREF=gi:15680248 /TID=Hs2.32...,BC014479,PX domain containing serine/threonine kinase,PXK,54899,NM_001289095 /// NM_001289096 /// NM_001289098...,0006468 // protein phosphorylation // non-trac...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // non-traceable...
24,1552275_s_at,BG573647,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:BG573647 /DB_XREF=gi:13581300 /DB_XREF=6025...,BG573647,PX domain containing serine/threonine kinase,PXK,54899,NM_001289095 /// NM_001289096 /// NM_001289098...,0006468 // protein phosphorylation // non-trac...,0005634 // nucleus // inferred from direct ass...,0000166 // nucleotide binding // non-traceable...

In [ ]:
gpl_df.tail(25)

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
54650,AFFX-r2-Bs-dap-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=dapB, jojF /DB_XREF=gb:L38424...",AFFX-r2-Bs-dap-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54651,AFFX-r2-Bs-lys-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54652,AFFX-r2-Bs-lys-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54653,AFFX-r2-Bs-lys-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=lys /DB_XREF=gb:X17013.1 /NOT...,AFFX-r2-Bs-lys-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54654,AFFX-r2-Bs-phe-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheB /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54655,AFFX-r2-Bs-phe-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheA /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54656,AFFX-r2-Bs-phe-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=pheA /DB_XREF=gb:M24537.1 /NO...,AFFX-r2-Bs-phe-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54657,AFFX-r2-Bs-thr-3_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrB /DB_XREF=gb:X04603.1 /NO...,AFFX-r2-Bs-thr-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54658,AFFX-r2-Bs-thr-5_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-r2-Bs-thr-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54659,AFFX-r2-Bs-thr-M_s_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-r2-Bs-thr-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54660,AFFX-r2-Ec-bioB-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54661,AFFX-r2-Ec-bioB-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54662,AFFX-r2-Ec-bioB-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioB /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioB-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54663,AFFX-r2-Ec-bioC-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioC /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioC-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54664,AFFX-r2-Ec-bioC-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioC /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioC-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54665,AFFX-r2-Ec-bioD-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioD /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioD-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54666,AFFX-r2-Ec-bioD-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,E. coli /GEN=bioD /DB_XREF=gb:J04423.1 /NOTE=S...,AFFX-r2-Ec-bioD-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54667,AFFX-r2-P1-cre-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,Bacteriophage P1 /GEN=cre /DB_XREF=gb:X03453.1...,AFFX-r2-P1-cre-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54668,AFFX-r2-P1-cre-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,Bacteriophage P1 /GEN=cre /DB_XREF=gb:X03453.1...,AFFX-r2-P1-cre-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54669,AFFX-ThrX-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrB /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54670,AFFX-ThrX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54671,AFFX-ThrX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-ThrX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54672,AFFX-TrpnX-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpC, trpF /DB_XREF=gb:K01391...",AFFX-TrpnX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54673,AFFX-TrpnX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpE, trpD /DB_XREF=gb:K01391...",AFFX-TrpnX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54674,AFFX-TrpnX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpD, trpC /DB_XREF=gb:K01391...",AFFX-TrpnX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
gpl_df.columns

Index(['ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date',
       'Sequence Type', 'Sequence Source', 'Target Description',
       'Representative Public ID', 'Gene Title', 'Gene Symbol',
       'ENTREZ_GENE_ID', 'RefSeq Transcript ID',
       'Gene Ontology Biological Process', 'Gene Ontology Cellular Component',
       'Gene Ontology Molecular Function'],
      dtype='object')

In [ ]:
deg_df.head()

             ID
0     1255_g_at
1    1552266_at
2    1552269_at
3  1552320_a_at
4  1552321_a_at

In [ ]:
deg_df.tail()

            ID
7407  34471_at
7408  37566_at
7409  51226_at
7410  65438_at
7411  91580_at

In [ ]:
deg_df.shape

(7412, 1)

In [ ]:
merged_df_3 = pd.merge(deg_df, gpl_df, on='ID')

In [ ]:
merged_df_3.dropna(subset=['Gene Symbol'], inplace=True)

In [ ]:
merged_df_3.shape

(4933, 16)

In [ ]:
gene_list = merged_df_3['Gene Symbol'].to_list()

In [ ]:
merged_df_3['Gene Symbol'].to_csv('gse112790.csv', index=False)

###TCGA

In [ ]:
tcga = pd.read_table('degs.txt', sep=' ')

In [ ]:
tcga.head()

,logFC,logCPM,LR,PValue,FDR,gene_name,gene_type
ENSG00000002079,1.995614,-0.386883,23.593691,1.189770e-06,8.161343e-06,MYH16,transcribed_unitary_pseudogene
ENSG00000002726,-2.145351,2.848888,26.285641,2.944699e-07,2.286535e-06,AOC1,protein_coding
ENSG00000003249,1.516839,5.866112,39.119183,3.987073e-10,4.978835e-09,DBNDD1,protein_coding
ENSG00000003987,1.658222,4.886749,29.221421,6.456148e-08,5.669198e-07,MTMR7,protein_coding
ENSG00000004838,1.801835,0.708423,41.608225,1.115231e-10,1.517960e-09,ZMYND10,protein_coding

In [ ]:
tcga.columns

Index(['logFC', 'logCPM', 'LR', 'PValue', 'FDR', 'gene_name', 'gene_type'], dtype='object')

In [ ]:
genes = tcga['gene_name'].reset_index(drop=True)

In [ ]:
genes.shape

(4412,)

In [ ]:
genes.to_csv('tcga_degs_extracted.csv', index=False)